import Head from 'next/head';

import Hero from '../components/Hero';
import QuoteSection from '../components/QuoteSection';
import ServiceSection from '../components/ServiceSection';
import BlogSection from '../components/BlogSection';

import styles from '../styles/Home.module.css';

export default function Index() {

	return (
		<div className={styles.container}>
			<Head>
				<title>SDS</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Hero />
			<ServiceSection />
			<QuoteSection />
			<BlogSection />
		</div>
	);
}
